CREATE TABLE IF NOT EXISTS currency
(
    currency_name  VARCHAR PRIMARY KEY,
    code_iso  INTEGER NOT NULL,
    exponent  INTEGER NOT NULL,
    crypto    BOOLEAN NOT NULL
);
CREATE TABLE IF NOT EXISTS transaction
(
    CURRENCY          VARCHAR NOT NULL,
    AMOUNT            REAL NOT NULL,
    STATE             VARCHAR NOT NULL,
    CREATED_DATE      TIMESTAMP NOT NULL,
    MERCHANT_CATEGORY VARCHAR NOT NULL,
    MERCHANT_COUNTRY  VARCHAR NOT NULL,
    ENTRY_METHOD      VARCHAR NOT NULL,
    USER_ID           SERIAL NOT NULL,
    TYPE              VARCHAR NOT NULL,
    SOURCE            VARCHAR NOT NULL,
    ID                VARCHAR NOT NULL
);